apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-p
spec:
  template:
    metadata:
      name: daemonset-p
      labels:
        app: my-nginx
    spec:
      containers:
      - name: daemonset-p
        image: nginx:1.22.1
        ports:
        - containerPort: 80

  selector:
    matchLabels:
      app: my-nginx
