apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-p
spec:
  selector:
    matchLabels:
      app: my-nginx
  replicas: 4
  template:
    metadata:
      name: nginx-temp-p
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1
        ports:
        - containerPort: 80






