apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  replicas: 5
  template:
    metadata:
      label: my-nginx
    spec:
      containers:
        - name: nginx 
          image: nginx:1.22.1
          ports:
            - containerPort: 80

selector:
  matchLabels:
    app: my-nginx